version: "3.4"

services:
  postgres:
    image: "postgres:14.5"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"

  redis:
    image: "redis:6.0.6"
    volumes:
      - "redis:/data"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    # env_file: ./.env # !!! OVERRIDE IN OTHER places
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    depends_on:
      - "postgres"
      - "redis"
    ports:
      - "3001:3000"

volumes:
  postgres:
  redis:
