version: "3.4"

services:
  postgres:
    container_name: weuse-api-postgres
  redis:
    container_name: weuse-api-redis
  app:
    build:
      dockerfile: ./docker/production/Dockerfile
    env_file: ./.production.env
    restart: always
    container_name: weuse-api-production
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=api.weuse.ru
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=api.weuse.ru
      - LETSENCRYPT_EMAIL=digitoider@gmail.com

networks:
  default:
    external:
      name: nginx-proxy
# [RUN:]
# docker-compose -f ./docker-compose.yml -f ./docker/production/docker-compose.yml build
# docker-compose -f ./docker-compose.yml -f ./docker/production/docker-compose.yml up -d
# docker-compose -f ./docker-compose.yml -f ./docker/production/docker-compose.yml down
